<a href="https://colab.research.google.com/github/kaiohas/DNC_Python/blob/main/Aula1_model_predict.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import seaborn as sns

In [39]:
dataset = sns.load_dataset("iris")
dataset.tail()

     sepal_length  sepal_width  petal_length  petal_width    species
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

In [40]:
x = dataset.iloc[:,:-1]
y = dataset.iloc[:,-1]

In [41]:
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [28]:
model = LogisticRegression()
model.fit(x_train,y_train)
x_test

LogisticRegression()

In [29]:
predict  = model.predict(x_test)
x_test

In [30]:
x_test['prediction'] = predict
y_test = pd.DataFrame(y_test)
x_test["real"]  = y_test['species']
x_test.head(20)

,sepal_length,sepal_width,petal_length,petal_width,prediction,real
16,5.4,3.9,1.3,0.4,setosa,setosa
34,4.9,3.1,1.5,0.2,setosa,setosa
55,5.7,2.8,4.5,1.3,versicolor,versicolor
8,4.4,2.9,1.4,0.2,setosa,setosa
110,6.5,3.2,5.1,2.0,virginica,virginica
91,6.1,3.0,4.6,1.4,versicolor,versicolor
39,5.1,3.4,1.5,0.2,setosa,setosa
123,6.3,2.7,4.9,1.8,virginica,virginica
2,4.7,3.2,1.3,0.2,setosa,setosa
115,6.4,3.2,5.3,2.3,virginica,virginica
49,5.0,3.3,1.4,0.2,setosa,setosa
63,6.1,2.9,4.7,1.4,versicolor,versicolor
33,5.5,4.2,1.4,0.2,setosa,setosa
103,6.3,2.9,5.6,1.8,virginica,virginica
117,7.7,3.8,6.7,2.2,virginica,virginica
81,5.5,2.4,3.7,1.0,versicolor,versicolor
72,6.3,2.5,4.9,1.5,versicolor,versicolor
138,6.0,3.0,4.8,1.8,virginica,virginica
82,5.8,2.7,3.9,1.2,versicolor,versicolor
20,5.4,3.4,1.7,0.2,setosa,setosa

In [57]:
from sklearn import preprocessing
df = pd.read_excel('/content/golf_df.xlsx')
le = preprocessing.LabelEncoder()
df['clima'] = le.fit_transform(df.clima.values)
df['temp'] = le.fit_transform(df.temp.values)
df['umidade'] = le.fit_transform(df.umidade.values)
df['vento'] = le.fit_transform(df.vento.values)
df['jogar'] = le.fit_transform(df.jogar.values)
df

    clima  temp  umidade  vento  jogar
0       2     1        0      0      0
1       2     1        0      1      0
2       0     1        0      0      1
3       1     2        0      0      1
4       1     0        1      0      1
5       1     0        1      1      0
6       0     0        1      1      1
7       2     2        0      0      0
8       2     0        1      0      1
9       1     2        1      0      1
10      2     2        1      1      1
11      0     2        0      1      1
12      0     1        1      0      1
13      1     2        0      1      0

In [58]:
x = df.iloc[:,:-1]
y = df[['jogar']]
y

    jogar
0       0
1       0
2       1
3       1
4       1
5       0
6       1
7       0
8       1
9       1
10      1
11      1
12      1
13      0

In [59]:
model = LogisticRegression()
model.fit(x,y)

/usr/local/lib/python3.9/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [60]:
predict  = model.predict(x)

In [65]:
x['prediction'] = predict
y_test = pd.DataFrame(y)
x["real"]  = y['jogar']
x.head(20)

    clima  temp  umidade  vento  prediction  real
0       2     1        0      0           0     0
1       2     1        0      1           0     0
2       0     1        0      0           1     1
3       1     2        0      0           1     1
4       1     0        1      0           1     1
5       1     0        1      1           1     0
6       0     0        1      1           1     1
7       2     2        0      0           0     0
8       2     0        1      0           1     1
9       1     2        1      0           1     1
10      2     2        1      1           1     1
11      0     2        0      1           1     1
12      0     1        1      0           1     1
13      1     2        0      1           1     0